name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Exécution quotidienne à minuit
  workflow_dispatch:     # Permet un déclenchement manuel
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Mise à jour recommandée ici aussi
      - uses: Platane/snk@master
        with:
          github_user_name: david15tonon
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4  # <-- Version corrigée !
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
      - name: Push to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update snake animation"
          git push
