name: Generate Snake Contribution SVG
on:
  schedule: [{ cron: "0 */12 * * *" }]    # Toutes les 12 heures
  workflow_dispatch:                      # Déclenchement manuel
  push: { branches: ["main", "master"] }  # Sur push

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Étape 1 : Générer le SVG
      - name: Generate Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: "david15tonon"  # À remplacer si besoin
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      # Étape 2 : Pousser vers la branche 'output'
      - name: Push to output branch
        uses: actions/checkout@v4
        with:
          ref: output  # Cible la branche 'output'

      - name: Commit & Push
        run: |
          mv github-contribution-grid-snake* . || true
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update snake: $(date +'%d/%m/%Y %H:%M')"
            git push
          else
            echo "No changes to commit"
          fi
