name: Generate Snake Animation
on:
  schedule: [{ cron: "0 */12 * * *" }]    # Runs every 12 hours
  workflow_dispatch:                      # Manual trigger
  push: { branches: ["main", "master"] }  # On push

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4
      
      # Step 2: Generate Snake SVG
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: "david15tonon"
          svg_out_path: "snake.svg"  # Simple output path

      # Step 3: Prepare output branch
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          path: output-files

      # Step 4: Copy and push files
      - name: Commit and Push
        run: |
          # Copy generated file
          cp snake.svg output-files/github-contribution-grid-snake.svg
          
          # Configure git
          cd output-files
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit changes
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update snake animation $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi
